project_name: miniboard
builds:
  - main: ./cmd/miniboard/
    binary: miniboard
    id: default
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm

nfpms:
  - maintainer: aceberg <aceberg_a@proton.me>
    description: Lightweight dashboard with tabs, uptime monitoring and notifications
    homepage: https://github.com/aceberg/miniboard
    license: MIT
    section: utils
    formats:
    - deb
    - rpm
    - apk
    - termux.deb
    contents:
    - src: ./configs/miniboard.service
      dst: /lib/systemd/system/miniboard.service
    - src: ./configs/miniboard@.service
      dst: /lib/systemd/system/miniboard@.service
    scripts:
      postinstall: ./configs/postinstall.sh

archives:
  - files:
    - LICENSE.md
    - README.md
    - CHANGELOG.md
    - src: ./configs/miniboard.service
      dst: miniboard.service
    - src: ./configs/miniboard@.service
      dst: miniboard@.service
    - src: ./configs/install.sh
      dst: install.sh
    wrap_in_directory: true
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: "checksums.txt"
