name: Readme-DockerHub

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - 'README.md'

env:
  IMAGE_NAME: miniboard

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync README.md to DockerHub
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          readme: "./README.md"

